[package]
name = "advent-of-code-2020"
license = "MIT"
readme = "README.md"
version = "0.1.0"
authors = ["Andreas Runfalk <andreas@runfalk.se>"]
edition = "2018"
publish = false


[dependencies]
anyhow = "1"
